name = "ENVI"
uuid = "cdc236e2-05f6-455d-8b36-4ce943f8ee7a"
authors = ["John Waczak <john.louis.waczak@gmail.com>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[compat]
julia = "1.8"
